# config/packages/knp_paginator.yaml
knp_paginator:
  page_range: 5                       # nombre de pages à afficher dans la pagination
  default_options:
    page_name: page                 # nom du paramètre de page
    sort_field_name: sort           # nom du paramètre de tri
    sort_direction_name: direction  # nom du paramètre de direction
    distinct: true                  # distinct results or not
  template:
    pagination: 'bundles/KnpPaginatorBundle/Pagination/bootstrap_v5_pagination.html.twig'
    sortable: 'bundles/KnpPaginatorBundle/Pagination/bootstrap_v5_sortable_link.html.twig'