<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240704083042 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create initial schema without redundant tables';
    }

    public function up(Schema $schema): void
    {
        // This migration auto-generated by the Doctrine ORM
        // Do not edit it manually unless necessary

        $this->addSql('CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, commercant_id INT NOT NULL, category_id INT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, price DOUBLE PRECISION NOT NULL, stock INT NOT NULL, INDEX IDX_23A0E66E9BBF1C (commercant_id), INDEX IDX_23A0E12469DE2 (category_id), PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE commande (id INT AUTO_INCREMENT NOT NULL, visiteur_id INT NOT NULL, status VARCHAR(255) NOT NULL, INDEX IDX_6EEAA67DAA9E377A (visiteur_id), PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE commercant (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE facture (id INT AUTO_INCREMENT NOT NULL, commande_id INT NOT NULL, total_price DOUBLE PRECISION NOT NULL, INDEX IDX_FE86641082EA2E54 (commande_id), PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE panier (id INT AUTO_INCREMENT NOT NULL, visiteur_id INT NOT NULL, UNIQUE INDEX UNIQ_24CC0DF82AA9E377A (visiteur_id), PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE visiteur (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE article_commande (article_id INT NOT NULL, commande_id INT NOT NULL, INDEX IDX_145FAA6C7294869C (article_id), INDEX IDX_145FAA6C9395C3F3 (commande_id), PRIMARY KEY(article_id, commande_id))');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66E9BBF1C FOREIGN KEY (commercant_id) REFERENCES commercant (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E12469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DAA9E377A FOREIGN KEY (visiteur_id) REFERENCES visiteur (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE86641082EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id)');
        $this->addSql('ALTER TABLE panier ADD CONSTRAINT FK_24CC0DF82AA9E377A FOREIGN KEY (visiteur_id) REFERENCES visiteur (id)');
        $this->addSql('ALTER TABLE article_commande ADD CONSTRAINT FK_145FAA6C7294869C FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_commande ADD CONSTRAINT FK_145FAA6C9395C3F3 FOREIGN KEY (commande_id) REFERENCES commande (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // This down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66E9BBF1C');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E12469DE2');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67DAA9E377A');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE86641082EA2E54');
        $this->addSql('ALTER TABLE panier DROP FOREIGN KEY FK_24CC0DF82AA9E377A');
        $this->addSql('ALTER TABLE article_commande DROP FOREIGN KEY FK_145FAA6C7294869C');
        $this->addSql('ALTER TABLE article_commande DROP FOREIGN KEY FK_145FAA6C9395C3F3');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE commercant');
        $this->addSql('DROP TABLE facture');
        $this->addSql('DROP TABLE panier');
        $this->addSql('DROP TABLE visiteur');
        $this->addSql('DROP TABLE article_commande');
    }
}
